name: Build ImmortalWrt x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-x86_64
        path: /home/runner/work/immortalwrt/immortalwrt/bin/targets/x86/generic/*
